#VENTANA
ANCHO_VENTANA = 1200
ALTO_VENTANA = 600

#CORDENADA DEL PISO
NIVEL_PISO = 552
NIVEL_TECHO = 50

#FOTOGRAMAS POR SEGUNDO
FPS = 120

#RUTA DE IMAGENES
RUTA_IMAGEN = r"C:\Users\lucia\Documents\Programacion I\JUEGO_V4\images\\"

#DIRECCION DONDE MIRA EL PERSONAJKE
IZQUIERDA = -1
DERECHA = 1

#TAMAÑO DE COLLIDERECT
ALTURA_PIES = 8 # Aprox Gravedad/2 + 1

#MODO DEBUG // DIBUJAR RECTANGULOS
DEBUG = False

#COLORES
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
CYAN = "#d7fcd4"
DORADO = "#b68f40"
