#VENTANA
ANCHO_VENTANA = 1200
ALTO_VENTANA = 600

#CORDENADA DEL PISO
GROUND_LEVEL = 550

#FOTOGRAMAS POR SEGUNDO
FPS = 60

#RUTA DE IMAGENES
PATH_IMAGE = r"C:\Users\lucia\Documents\Programacion I\JUEGO_V3\images\\"

#DIRECCION DONDE MIRA EL PERSONAJKE
DIRECTION_L = 0
DIRECTION_R = 1

#TAMAÑO DE COLLIDERECT
GROUND_COLLIDE_H = 8 # Aprox Gravedad/2 + 1

#MODO DEBUG // DIBUJAR RECTANGULOS
DEBUG = False

#COLORES
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)